image: "rust:latest"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/

rustfmt:
  stage: build
  cache: {}
  script:
    - rustup component add rustfmt
    - cargo fmt --version
    - cargo fmt -- --check

clippy:
  stage: build
  script:
    - rustup component add clippy
    - cargo clippy --version
    - cargo clippy -- -D warnings

build:
  stage: build
  script:
    - rustc --version && cargo --version
    - cargo build --workspace --verbose

test:
  stage: test
  needs: [build]
  script:
    - rustc --version && cargo --version
    - cargo test --workspace --verbose
